language: python
python:
- 3.8
- 3.7
- 3.6
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: VStiNuV6eJmFIwLuyMi6xcz0vzxFBvTQ/seWlaLhtYCG6rq0AtugyXX1VJsTkQmcq9aqYyw4zPHzXxJy1sHgtpXxC4h4h8qjE+4EW3wvz8tQ5NRklJ8OyQSn5NHvh4uAWu/NYz++H6OboX17B5ssmIyuwM3dwrgUQK3jZtFeEh5eENBvNj6Te7BUrGR0JNk1slBeQJ9fJVLlR5/L8Bx28QT05jHJGbDHUgjHJXe6k3sioey4sYAQ3cEJEszzfwxmMSLbWMRsYxZO/GQ3Ig8cxROcV4CfMhEBweuInrsGXoHEByYXVReDouUxvKgfEjoFGibgObaGt1xnzsvjcsdBlLCJDRUg8EqMBDhSjkgCGzEKp8o7EAx9t2Pwc5j3OkTuQumdIYKznSYLNckSNR3tqe7H3nar4+U/aX+zFi49S4yAFlz/KmMVyvBW/gRs7ZrYA36fS7s6jsFKkwk5GPqyNzIaaKxNfD7sVDLvJ4W0zJ9zzsWA6OEhbvXneNFBMVd8wGxlJgTvKk3pqKNh03ERV4VITDuFpI6D6seb3LYsLoJULkrO4lFcFTY/LP0j8shgyqSET1XrscjpcAZUOwxvw9A9LOowRWXxXzce4u/XDIKQbw2yivpTK+cDn+v2ZE1mxDYp6BeEY5ePFa4y8B4RbeozfjVZVVtt0KOO+auh1Aw=
  on:
    tags: true
    branch: master
    python: 3.8
