name: Publish to AWS CodeArtifact

on: workflow_dispatch

env:
  CODEARTIFACT_URL: https://robbin-906828889059.d.codeartifact.us-east-1.amazonaws.com/pypi/pypi/
  CODEARTIFACT_DOMAIN: robbin
  AWS_OWNER: 906828889059

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${AWS_OWNER}:role/github
          aws-region: us-east-1

      - name: Configure CodeArtifact in .pypirc
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${CODEARTIFACT_DOMAIN} --domain-owner ${AWS_OWNER} --query authorizationToken --output text)
          echo "[distutils]" > ~/.pypirc
          echo "index-servers =" >> ~/.pypirc
          echo "    codeartifact" >> ~/.pypirc
          echo "" >> ~/.pypirc
          echo "[codeartifact]" >> ~/.pypirc
          echo "repository: ${CODEARTIFACT_URL}" >> ~/.pypirc
          echo "username: aws" >> ~/.pypirc
          echo "password: ${CODEARTIFACT_AUTH_TOKEN}" >> ~/.pypirc

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to CodeArtifact
        run: twine upload --repository codeartifact dist/*